### PR TITLE
Add option for Cybersyn stations to automatically be renamed during poll

### PR DESCRIPTION
**Pull request by PeteyPii**
The naming pattern can be decided by users (for now supporting only a simple set of substitutions).

NOTE: The debug revision is set and the migration code sets all stations to turn the renaming on (useful for testing, unsafe for a real release)

Settings:
image

Combinator:
image

In game example:
image

### CODE REVIEW

**Comment by jagoly** [comment]
I wonder if a better default for naming might be something that only uses icons? that way it's language independent

**Comment by jagoly** [comment]
One more point, IMO whether a station is listed as a provider/requester shouldn't depend on there being signals, rather it should only depend on is_r or is_p being set. This way it's clear what mode a station is set to, and it has the bonus of annoying people that just leave every station on both modes so that they might actually set the mode properly to get free UPS and avoid some footguns.

**Comment by jagoly** [comment]
https://github.com/PeteyPii/project-cybersyn/pull/1

made a PR for this PR because I couldn't work out how to add it is a review

**Comment by Eldrinn-Elantey** [comment]
And you can make it so that the name of the surface is added to the beginning of the name of the station. For example "Nauvis:"

**Comment by Eldrinn-Elantey** [comment]
The names of the surfaces are not localized. And as I noticed in SE, only the starting planet is written with a small letter

**Comment by Tetlanesh** [comment]
Closing all pre 2.0 PR's. If it is still relevant reopen the PR or submit a new one.

**Pull request closed without merging**
